# spring boot 配置
spring:
  devtools:
    restart:
      enabled: true
  profiles:
    # 选择运行环境对应的配置文件
    active: dev
  mvc:
    format:
      # 日期格式化
      date: yyyyMMdd
  thymeleaf:
    # 关闭模板引擎缓存
    cache: false
  messages:
    # 国际化配置
    basename: i18n.message
    # 直接使用H5框架
    # mode: HTML
server:
  shutdown: graceful

# 可查看哪些自动配置类生效
debug: false

# 单yaml内多环境配置
# 生产环境配置
---
server:
  port: 8180
spring:
  config:
    activate:
      on-profile: prod1
# 开发环境配置
---
server:
  port: 8181
spring:
  config:
    activate:
      on-profile: dev1
# 测试环境配置
---
server:
  port: 8182
spring:
  config:
    activate:
      on-profile: test1